api/urls.py
from . import views
from django.urls import path

# TEMPLATE TAGGING
app_name = 'bdcovidapi'

urlpatterns = [
    path('', views.home, name='home'),
    path('districts', views.getDistrictData, name='districts'),
    path('divisions', views.getDivisionData, name='divisions'),
    path('status', views.getStatus, name='status'),
    path('about', views.about, name='about')
]

covidbd/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls'))
]

api/models.py
from django.db import models

# Create your models here.

api/views.py
import os
import math
import json
import requests
from bs4 import BeautifulSoup as bs
from datetime import datetime

from django.shortcuts import render
from django.views.generic import View
from django.core.serializers import serialize
from django.http import JsonResponse, HttpResponse

def getURL():
    url = os.environ.get("SET_LINK")
    return url

def getDistricts():
    url = getURL()
    response = requests.get(url)
    html = response.content

    soup = bs(html, 'html.parser')
    table = soup.find('div', attrs={'class': 'ritz grid-container'})
    tbody = table.find('tbody')
    districts = tbody.find_all('tr')
    return districts

def getCountNumber(number):
    try:
        return int(number)
    except ValueError:
        return int(0)
        
def getLastUpdatedDate():
    districts = getDistricts()

    indx = 0
    date = ''
    for dist in districts:
        indx = indx + 1

        if (indx == 3):
            distrow = dist.find_all('td')
            distData = [distcol.text.strip() for distcol in distrow]
            date = distData[4]

    return date

def home(request):
    data = { "end_point" : 'http://localhost' }
    return render(request, 'home.html', context=data)

def getDistrictData(request):
    districts = getDistricts()

    data = []
    indx = 0
    districtIdMap = [3, 17, 28, 32, 40, 50, 54, 60]
    districtNameIdMap = [54, 60]
    districtMapValue = ['Barguna', 'Joypurhat']
    for dist in districts:
        indx = indx + 1

        if (indx <= 2):
            continue
        if (indx == 68):
            break

        distrow = dist.find_all('td')
        distData = [distcol.text.strip() for distcol in distrow]

        if (indx in districtIdMap):
            distNameMap = distData[0]
            if (indx in districtNameIdMap):
                if (indx == 54):
                    distNameMap = districtMapValue[0]
                else:
                    distNameMap = districtMapValue[1]
            
            distObj = {
                "id" : indx,
                "name" : distNameMap,
                "count" : getCountNumber(distData[2])
            }
            data.append(distObj)
        else:
            distObj = {
                "id" : indx,
                "name" : distData[0],
                "count" : getCountNumber(distData[1])
            }
            data.append(distObj)
    
    distFinalObj = {
        "district": data,
        "updated_on" : getLastUpdatedDate()
    }

    distFinalData = json.dumps(distFinalObj)
    return HttpResponse(distFinalData, content_type="application/json")
        
def getDivisionData(request):
    districts = getDistricts()
    divisionIdMap = [3, 17, 28, 32, 40, 50, 54, 60]
    divisionMapValue = ['Dhaka', 'Chattogram', 'Sylhet', 'Rangpur', 'Khulna', 'Mymensingh', 'Barishal', 'Rajshahi']
    
    data = []
    indx = 0
    countDiv = 1
    for dist in districts:
        indx = indx + 1

        if (indx in divisionIdMap):
            distrow = dist.find_all('td')
            distData = [distcol.text.strip() for distcol in distrow]

            divObj = {
                "id" : countDiv,
                "name" : divisionMapValue[countDiv-1],
                "total" : getCountNumber(distData[3])
            }

            countDiv = countDiv + 1
            data.append(divObj)
            
    divFinalObj = {
        "division": data,
        "updated_on" : getLastUpdatedDate()
    }

    divFinalData = json.dumps(divFinalObj)
    return HttpResponse(divFinalData, content_type="application/json")

def getStatus(request):
    url = getURL()
    response = requests.get(url)
    status = response.content

    return HttpResponse(status, content_type="application/json")

def about(request):
    data = {
        "info": {
            "name": "Dipta Dhar",
            "github": "github.com/dipta-dhar",
            "intro": "Think simply & solve complex world"
        }
    }
    finalData = json.dumps(data)
    return HttpResponse(finalData, content_type="application/json")

templates/base.html
<!doctype html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title_name %} covid-bd api  {% endblock title_name %}</title>

    <link rel="icon" href="./../static/images/favicon.ico"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
    <link rel="stylesheet" href="./../static/css/mystyle.css" />
</head>
<body class="bg-dark text-light">
    <div class="container my-4">
        {% comment %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'bdcovidapi:home' %}">INDEX</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'bdcovidapi:home' %}">home</a>
                    <a class="nav-item nav-link" href="{% url 'bdcovidapi:districts' %}">districts</a>
                    <a class="nav-item nav-link" href="{% url 'bdcovidapi:districts' %}">districts</a>
                </div>
            </div>
        </nav>
        {% endcomment %}
    </div>

    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

    <!-- require JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-primary">An open API For BD Covid-19</h1>

    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">METHOD</th>
            <th scope="col">LINK</th>
            <th scope="col">DESCRIPTION</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td ></td><td></td><td></td>
          </tr>
          <tr>
            <td scope="row" class="method-cls br-cls"> GET </td>
            <td class="link-cls br-cls"><a href="{% url 'bdcovidapi:districts' %}" target="_blank">{{ end_point }}/districts</a></td>
            <td class="desc-cls">Get all district wise data</td>
          </tr>
          <tr>
            <td ></td><td></td><td></td>
          </tr>
          <tr>
            <td scope="row" class="method-cls br-cls"> GET </td>
            <td class="link-cls br-cls"><a href="{% url 'bdcovidapi:divisions' %}" target="_blank">{{ end_point }}/divisions</a></td>
            <td class="desc-cls">Get all division wise data</td>
          </tr>
          <tr>
            <td ></td><td></td><td></td>
          </tr>
          <tr>
            <td scope="row" class="method-cls br-cls"> GET </td>
            <td class="link-cls br-cls"><a href="{% url 'bdcovidapi:status' %}" target="_blank">{{ end_point }}/status</a></td>
            <td class="desc-cls">Get all status data</td>
          </tr>
          <tr>
            <td ></td><td></td><td></td>
          </tr>
          <tr>
            <td scope="row" class="method-cls br-cls"> GET </td>
            <td class="link-cls br-cls"><a href="{% url 'bdcovidapi:about' %}" target="_blank">{{ end_point }}/about</a></td>
            <td class="desc-cls">About me</td>
          </tr>
        </tbody>
    </table>

    <div class="myfooter">
      Made with <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="heart" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="heart-icon"><path fill="currentColor" d="M462.3 62.6C407.5 15.9 326 24.3 275.7 76.2L256 96.5l-19.7-20.3C186.1 24.3 104.5 15.9 49.7 62.6c-62.8 53.6-66.1 149.8-9.9 207.9l193.5 199.8c12.5 12.9 32.8 12.9 45.3 0l193.5-199.8c56.3-58.1 53-154.3-9.8-207.9z" class=""></path></svg> by<a class="github" href="https://github.com/dipta-dhar" target="_blank"> Dipta</a>
    </div>
    
{% endblock content %}